=== Lazavenka/task03XMLParser/src/main/resources/data/tariffs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.lozovenko.by/tariffs"
        xmlns:tns="http://www.lozovenko.by/tariffs"
        elementFormDefault="qualified">
    <element name="AbstractTariffs">
        <complexType>
            <sequence>
                <element ref="tns:Tariffs" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="TariffType">
        <sequence>
            <element name="name" type="string"/>
            <element name="payroll" type="tns:NonNegativeDouble"/>
            <element name="tariffParameters" type="tns:TariffParameters"/>
            <element name="operator">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="A1"/>
                        <enumeration value="MTS"/>
                        <enumeration value="LIFE"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="tariffId" type="tns:TariffID" use="required"/>
    </complexType>
    <complexType name="InternetTariffType">
        <complexContent>
            <extension base="tns:TariffType">
                <sequence>
                    <element name="includeTraffic" type="tns:Traffic"/>
                    <element name="trafficCostOverIncluded" type="tns:NonNegativeDouble"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="TariffParameters">
        <sequence>
            <element name="favouriteNumbers" type="nonNegativeInteger"/>
            <element name="connectionPayment" type="tns:NonNegativeDouble"/>
            <element name="billing">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="SECOND"/>
                        <enumeration value="TVELVESECOND"/>
                        <enumeration value="MINUTE"/>
                        <enumeration value="NONE"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
    <complexType name="SmartphoneTariffType">
        <complexContent>
            <extension base="tns:TariffType">
                <sequence>
                    <element name="includedMinutes" type="nonNegativeInteger"/>
                    <element name="includeTraffic" type="tns:Traffic"/>
                    <element name="trafficCostOverIncluded" type="tns:NonNegativeDouble"/>
                    <element name="callPrice" type="tns:CallPrise"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="MobileTariffType">
        <complexContent>
            <extension base="tns:TariffType">
                <sequence>
                    <element name="includedMinutes" type="nonNegativeInteger"/>
                    <element name="callPrice" type="tns:CallPrise"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Traffic">
        <sequence>
            <element name="value" type="nonNegativeInteger"/>
        </sequence>
        <attribute name="unit" type="tns:TrafficType" use="required"/>
    </complexType>
    <complexType name="CallPrise">
        <sequence>
            <element name="insideNetworkCallPrice" type="tns:NonNegativeDouble"/>
            <element name="outsideNetworkCallPrice" type="tns:NonNegativeDouble"/>
            <element name="stationaryPhoneCallPrice" type="tns:NonNegativeDouble"/>
        </sequence>
    </complexType>
    <simpleType name="NonNegativeDouble">
        <restriction base="double">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>
    <simpleType name="TrafficType">
        <restriction base="string">
            <enumeration value="KB"/>
            <enumeration value="MB"/>
            <enumeration value="GB"/>
        </restriction>
    </simpleType>
    <simpleType name="TariffID">
        <restriction base="ID">
            <pattern value="ID-[0-9][0-9][0-9][0-9]"/>
        </restriction>
    </simpleType>
    <element name="Tariffs" type="tns:TariffType" abstract="true"/>
    <element name="internetTariff" type="tns:InternetTariffType" substitutionGroup="tns:Tariffs"/>
    <element name="smartphoneTariff" type="tns:SmartphoneTariffType" substitutionGroup="tns:Tariffs"/>
    <element name="mobileTariff" type="tns:MobileTariffType" substitutionGroup="tns:Tariffs"/>
</schema>

=== Lazavenka/task03XMLParser/src/main/resources/data/test/test2.xml
<?xml version="1.0" encoding="UTF-8" ?>

<AbstractTariffs xmlns="http://www.lozovenko.by/tariffs"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.lozovenko.by/tariffs //tariffs.xsd">
    <mobileTariff tariffId="ID-1234">
        <name>TestMobile</name>
        <payroll>1</payroll>
        <tariffParameters>
            <favouriteNumbers>1</favouriteNumbers>
            <connectionPayment>1</connectionPayment>
            <billing>SECOND</billing>
        </tariffParameters>
        <operator>LIFE</operator>
        <includedMinutes>1</includedMinutes>
        <callPrice>
            <insideNetworkCallPrice>1</insideNetworkCallPrice>
            <outsideNetworkCallPrice>1</outsideNetworkCallPrice>
            <stationaryPhoneCallPrice>1</stationaryPhoneCallPrice>
        </callPrice>
    </mobileTariff>
</AbstractTariffs>

=== Lazavenka/task03XMLParser/src/main/resources/data/test/test1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<AbstractTariffs xmlns="http://www.lozovenko.by/tariffs"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.lozovenko.by/tariffs //tariffs.xsd">
    <smartphoneTariff tariffId="ID-9999">
        <name>TestName</name>
        <payroll>99.999</payroll>
        <tariffParameters>
            <favouriteNumbers>10</favouriteNumbers>
            <connectionPayment>10.001</connectionPayment>
            <billing>MINUTE</billing>
        </tariffParameters>
        <operator>MTS</operator>
        <includedMinutes>1000</includedMinutes>
        <includeTraffic unit="MB">
            <value>1000</value>
        </includeTraffic>
        <trafficCostOverIncluded>0.05</trafficCostOverIncluded>
        <callPrice>
            <insideNetworkCallPrice>0.01</insideNetworkCallPrice>
            <outsideNetworkCallPrice>0.04</outsideNetworkCallPrice>
            <stationaryPhoneCallPrice>0.12</stationaryPhoneCallPrice>
        </callPrice>
    </smartphoneTariff>
</AbstractTariffs>
